#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
clear
MYIP=$(wget -qO- ipinfo.io/ip)
DATANAME=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $2}')
DATADATE=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $3}')
DATAIP=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $4}')
TODAY=$(date -I)
CEKDATE() {
    exp=$DATADATE
    d1=($(date -d "$DATADATE" +%s))
    d2=($(date -d "$TODAY" +%s))
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        echo "Expired"
        sleep 5
        menu
    else
        echo "Permission Accepted..."
    fi
}
CEKIP() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | awk '{print $4}' | grep $MYIP)
    if [ "$MYIP" = "$IZIN" ]; then
        CEKDATE
    else
    echo "Permission Denied!"
    sleep 5
    menu
    fi
}
CEKIP
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo -e "\e[42m         Add Xray/Vless Account          \E[0m"
  echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

  read -rp "User: " -e user
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[42m         Add Xray/Vless Account          \E[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
    echo "A client with the specified name was already created, please choose another name."
    echo ""
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
  fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
read -p "Limit User (GB): " Quota
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
cat >/var/www/vless-$user.txt <<-END
_______________________________________________________
           Thank You For Using Our Services
                Xray/Vless Account
        Autoscript xray-lite dev bhoikfostyahya
_____________________script v.2_________________________
      System Request:Debian 9+/Ubuntu 18.04+/20+
      Author:	bhoikfostyahya
      Dscription: Xray Menu Management
      email: bhoikfostyahya@gmail.com
      telegram: https://t.me/bhoikfost_yahya
      installer script :
source <(curl -sL https://sc-xray.yha.my.id/ub20.sh)
_______________________________________________________
              Format Vless WS (CDN)
_______________________________________________________

- name: Vless-$user-WS (CDN)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
_______________________________________________________
              Format Vless WS (CDN) Non TLS
_______________________________________________________
- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true
_______________________________________________________
              Format Vless gRPC (SNI)
_______________________________________________________
- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: multi
  grpc-service-name: vless-grpc
  udp: true

_______________________________________________________
              Link Vless Account
_______________________________________________________
Link TLS : vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}
_______________________________________________________
Link none TLS : vless://${uuid}@${domain}:80?path=/vless&security=tls&encryption=none&host=${domain}&type=ws#${user}
_______________________________________________________
Link GRPC :vless://${uuid}@${domain}:443?mode=multi&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}
_______________________________________________________
vless://uuid@address:443?encryption=none&security=tls&sni=sni&type=ws&host=host&path=path#alias




END
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&security=tls&encryption=none&host=${domain}&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=multi&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
systemctl restart xray
systemctl restart nginx
service cron restart
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp} ${uuid}" >>/etc/vless/.vless.db

clear
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "\e[42m    Xray/Vless Account     \E[0m" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "Remarks    : ${user}" | tee -a /etc/log-create-user.log
echo -e "Domain     : ${domain}" | tee -a /etc/log-create-user.log
echo -e "Location   : $CITY" | tee -a /etc/log-create-user.log
echo -e "User Quota : ${Quota} GB" | tee -a /etc/log-create-user.log
echo -e "port TLS   : 443" | tee -a /etc/log-create-user.log
echo -e "Port NTLS  : 80, 8080, 2086" | tee -a /etc/log-create-user.log
echo -e "User ID    : ${uuid}" | tee -a /etc/log-create-user.log
echo -e "Encryption : none" | tee -a /etc/log-create-user.log
echo -e "Path TLS   : /vless " | tee -a /etc/log-create-user.log
echo -e "ServiceName: vless-grpc" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "Link TLS   : ${vlesslink1}" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "Link NTLS  : ${vlesslink2}" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "Link GRPC  : ${vlesslink3}" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "Expired On : $exp" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "" | tee -a /etc/log-create-user.log
read -n 1 -s -r -p "Press any key to back on menu"

menu
