#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
TIMES="10"
CHATID="0123456789"
KEY="5877606689:AAGALvW_WdeVCdCf3tlQSvBGOJZ0SRTymRA"
URL="https://api.telegram.org/bot$KEY/sendMessage"
MYIP=$(wget -qO- ipinfo.io/ip)
DATANAME=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $2}')
DATADATE=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $3}')
DATAIP=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $4}')
TODAY=$(date -I)
CEKDATE() {
    exp=$DATADATE
    d1=($(date -d "$DATADATE" +%s))
    d2=($(date -d "$TODAY" +%s))
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        echo "Expired"
        sleep 5
        menu
    else
        echo "Permission Accepted..."
    fi
}
CEKIP() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | awk '{print $4}' | grep $MYIP)
    if [ "$MYIP" = "$IZIN" ]; then
        CEKDATE
    else
    echo "Permission Denied!"
    sleep 5
    menu
    fi
}
CEKIP
echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\e[42m              SSH Ovpn Account           \E[0m"
echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -p "Username : " LOGIN
read -p "Password : " PASSWD
read -p "Expired (hari): " EXPIRED
IP=$(curl -sS ifconfig.me)
CITY=$(cat /etc/xray/city)
PUB=$( cat /etc/slowdns/server.pub )
NS=`cat /etc/xray/dns`
domain=`cat /etc/xray/domain`
useradd -e `date -d "$EXPIRED days" +"%Y-%m-%d"` -s /bin/false -M $LOGIN
exp="$(chage -l $LOGIN | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$PASSWD\n$PASSWD\n"|passwd $LOGIN &> /dev/null

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${LOGIN}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${LOGIN}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${LOGIN}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${LOGIN} " >>/etc/ssh/.ssh.db

cat > /var/www/ssh-$LOGIN.txt <<-END
_______________________________________________________
           Thank You For Using Our Services
                 SSH OVPN Account 
        Autoscript xray-lite dev bhoikfostyahya
_____________________script v.2_________________________
      System Request:Debian 9+/Ubuntu 18.04+/20+
      Author:	bhoikfostyahya
      Dscription: SSH Menu Management
      email: bhoikfostyahya@gmail.com
      telegram: https://t.me/bhoikfost_yahya
      installer script :
source <(curl -sL https://sc-xray.yha.my.id/ub20.sh)
_______________________________________________________
              Format SSH OVPN Account
_______________________________________________________

Username         : $LOGIN
Password         : $PASSWD
Expired          : $exp
__________________________________
IP               : $IP
Host             : $domain
Host Slowdns     : ${NS}
Pub Key          : ${PUB}
Location         : $CITY
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH WS      : 80
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
Proxy Squid      : 3128, 8000
BadVPN UDP       : 7100, 7300, 7300
__________________________________
Payload WSS: CF-RAY wss://$domain/ HTTP/1.1[crlf]Host: BUG.COM[crlf]Upgrade: websocket[crlf][crlf] 
__________________________________
OpenVPN WS SSL : http://$domain:81/ws-ssl.ovpn
OpenVPN SSL : http://$domain:81/ssl.ovpn
OpenVPN TCP : http://$domain:81/tcp.ovpn
OpenVPN UDP : http://$domain:81/udp.ovpn
__________________________________

END
TEXT="
<code>───────────────────────────</code>
<code>      SSH OVPN Account     </code>
<code>───────────────────────────</code>
<code>Username         : $LOGIN</code>
<code>Password         : $PASSWD</code>
<code>Expired          : $exp</code>
<code>───────────────────────────</code>
<code>IP               : $IP</code>
<code>Host             : $domain</code>
<code>Host Slowdns     : ${NS}</code>
<code>Pub Key          : ${PUB}</code>
<code>Location         : $CITY</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port Dropbear WS : 443, 109</code>
<code>Port SSH WS      : 80 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 443</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>Proxy Squid      : 3128, 8000</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>───────────────────────────</code>
<code>Payload WSS      : </code><code>CF-RAY wss://$domain/ HTTP/1.1[crlf]Host: BUG.COM[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>───────────────────────────</code>
<code>OpenVPN WS SSL   : </code>http://$domain:81/ws-ssl.ovpn
<code>OpenVPN SSL      : </code>http://$domain:81/ssl.ovpn
<code>OpenVPN TCP      : </code>http://$domain:81/tcp.ovpn
<code>OpenVPN UDP      : </code>http://$domain:81/udp.ovpn
<code>───────────────────────────</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
clear
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "\e[42m      SSH OVPN Account     \E[0m" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "Username         : $LOGIN" | tee -a /etc/log-create-user.log
echo -e "Password         : $PASSWD" | tee -a /etc/log-create-user.log
echo -e "Expired          : $exp" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "IP               : $IP" | tee -a /etc/log-create-user.log
echo -e "Host             : $domain" | tee -a /etc/log-create-user.log
echo -e "Host Slowdns     : ${NS}" | tee -a /etc/log-create-user.log
echo -e "Pub Key          : ${PUB}" | tee -a /etc/log-create-user.log
echo -e "Location         : $CITY" | tee -a /etc/log-create-user.log
echo -e "Port OpenSSH     : 443, 80, 22" | tee -a /etc/log-create-user.log
echo -e "Port Dropbear    : 443, 109" | tee -a /etc/log-create-user.log
echo -e "Port Dropbear WS : 443, 109" | tee -a /etc/log-create-user.log
echo -e "Port SSH WS      : 80 " | tee -a /etc/log-create-user.log
echo -e "Port SSH SSL WS  : 443" | tee -a /etc/log-create-user.log
echo -e "Port SSL/TLS     : 443" | tee -a /etc/log-create-user.log
echo -e "Port OVPN WS SSL : 443" | tee -a /etc/log-create-user.log
echo -e "Port OVPN SSL    : 443" | tee -a /etc/log-create-user.log
echo -e "Port OVPN TCP    : 443, 1194" | tee -a /etc/log-create-user.log
echo -e "Port OVPN UDP    : 2200" | tee -a /etc/log-create-user.log
echo -e "Proxy Squid      : 3128, 8000" | tee -a /etc/log-create-user.log
echo -e "BadVPN UDP       : 7100, 7300, 7300" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "Payload WSS      : CF-RAY wss://$domain/ HTTP/1.1[crlf]Host: BUG.COM[crlf]Upgrade: websocket[crlf][crlf]" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "OpenVPN WS SSL   : http://$domain:81/ws-ssl.ovpn" | tee -a /etc/log-create-user.log
echo -e "OpenVPN SSL      : http://$domain:81/ssl.ovpn" | tee -a /etc/log-create-user.log
echo -e "OpenVPN TCP      : http://$domain:81/tcp.ovpn" | tee -a /etc/log-create-user.log
echo -e "OpenVPN UDP      : http://$domain:81/udp.ovpn" | tee -a /etc/log-create-user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/log-create-user.log
echo -e "" | tee -a /etc/log-create-user.log
read -n 1 -s -r -p "Press any key to back on menu"
menu
