#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
MYIP=$(wget -qO- ipinfo.io/ip)
DATANAME=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $2}')
DATADATE=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $3}')
DATAIP=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | grep $MYIP | awk '{print $4}')
TODAY=$(date -I)
CEKDATE() {
    exp=$DATADATE
    d1=($(date -d "$DATADATE" +%s))
    d2=($(date -d "$TODAY" +%s))
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        echo "Expired"
        sleep 5
        menu
    else
        echo "Permission Accepted..."
    fi
}
CEKIP() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/ayaze01/clash/main/mm/ip | awk '{print $4}' | grep $MYIP)
    if [ "$MYIP" = "$IZIN" ]; then
        CEKDATE
    else
    echo "Permission Denied!"
    sleep 5
    menu
    fi
}
CEKIP
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/trojan/.trojan.db")
if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo -e "\e[42m            Delete Trojan Account        \E[0m"
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo ""
    echo "You have no existing clients!"
    echo ""
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
fi

clear
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo -e "\e[42m            Delete Trojan Account        \E[0m"
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo "     NO    User    Expired  "
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
echo ""
red "tap enter to go back"
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
grep -E "^### " "/etc/trojan/.trojan.db" | cut -d ' ' -f 2-3 | nl -s ') '
until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
    if [[ ${CLIENT_NUMBER} == '1' ]]; then
        read -rp "Select one client [1]: " CLIENT_NUMBER
    else
        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
    fi
done
user=$(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
systemctl restart xray
clear
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo " Trojan Account Deleted Successfully"
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo " Client Name : $user"
echo " Expired On  : $exp"
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
