#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
Font="\033[0m"
gray="\e[1;30m"
total_ram=$(grep "MemTotal: " /proc/meminfo | awk '{ print $2}')
totalram=$(($total_ram / 1024))
MYIP=$(curl -sS ipv4.icanhazip.com)
LAST_DOMAIN="$(cat /etc/xray/domain)"
GITHUB_CMD="http://aa.cemilan-vpn.my.id:81/"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }

function print_ok() {
    echo -e "${OK} ${BLUE} $1 ${FONT}"
}

function print_error() {
    echo -e "${ERROR} ${REDBG} $1 ${FONT}"
}

judge() {
    if [[ 0 -eq $? ]]; then
        print_ok "$1 Complete... | thx to ${YELLOW}bhoikfostyahya${FONT}"
        sleep 1
    fi
}

function get_acme_domain() {

    echo -e "${GREEN}--->${NC}     Start "
    systemctl stop nginx
    systemctl stop haproxy
    echo -e "${GREEN}--->${NC}     Starting renew cert "
    sleep 2
    echo -e "${GREEN}--->$NC     Getting acme for cert"
    /root/.acme.sh/acme.sh --upgrade --auto-upgrade >/dev/null 2>&1
    /root/.acme.sh/acme.sh --set-default-ca --server letsencrypt >/dev/null 2>&1
    /root/.acme.sh/acme.sh --issue -d $domain --standalone -k ec-256 >/dev/null 2>&1
    /.acme.sh/acme.sh --installcert -d $domain --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key --ecc >/dev/null 2>&1
    echo -e "${GREEN}--->${NC}     Renew cert done "
    sed -i "s/${LAST_DOMAIN}/${domain}/g" /etc/nginx/conf.d/xray.conf >/dev/null 2>&1
    sed -i "s/${LAST_DOMAIN}/${domain}/g" /var/www/html/index.html >/dev/null 2>&1
    sed -i "s/${LAST_DOMAIN}/${domain}/g" /etc/haproxy/haproxy.cfg >/dev/null 2>&1
    judge "Installed slowdns"
    wget -q -O /etc/nameserver "${GITHUB_CMD}main/X-SlowDNS/nameserver" && bash /etc/nameserver >/dev/null 2>&1
    systemctl daemon-reload >/dev/null 2>&1
    systemctl restart server >/dev/null 2>&1
    systemctl restart client >/dev/null 2>&1
    systemctl restart haproxy >/dev/null 2>&1
    systemctl restart nginx >/dev/null 2>&1
    systemctl restart xray >/dev/null 2>&1
    sleep 5
    echo ""
    echo ""
    read -n 1 -s -r -p "Press any key to back on menu"

    menu
}

function renew_domain() {
    read -rp "Input ur Domain/Host : " -e domain
    rm -rf /etc/xray/domain
    echo $domain >/etc/xray/domain
    get_acme_domain
}

cloudflare() {

    DOMEN="vpn-server.my.id"
    sub=$(tr </dev/urandom -dc a-z0-9 | head -c5)
    domain="cloud-${sub}.vpn-server.my.id"
    echo -e "${domain}" >/etc/xray/domain
    CF_ID="ruangtambahan1@gmail.com"
    CF_KEY="bb2a2607ea3abbfe4ab4ac9195f48fc725a3b"
    set -euo pipefail
    IP=$(wget -qO- ipinfo.io/ip)
    echo -e "Updating DNS for ${gray}${domain}${Font}"
    ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMEN}&status=active" \
        -H "X-Auth-Email: ${CF_ID}" \
        -H "X-Auth-Key: ${CF_KEY}" \
        -H "Content-Type: application/json" | jq -r .result[0].id)

    RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${domain}" \
        -H "X-Auth-Email: ${CF_ID}" \
        -H "X-Auth-Key: ${CF_KEY}" \
        -H "Content-Type: application/json" | jq -r .result[0].id)

    if [[ "${#RECORD}" -le 10 ]]; then
        RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
            -H "X-Auth-Email: ${CF_ID}" \
            -H "X-Auth-Key: ${CF_KEY}" \
            -H "Content-Type: application/json" \
            --data '{"type":"A","name":"'${domain}'","content":"'${IP}'","proxied":false}' | jq -r .result.id)
    fi

    RESULT=$(curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
        -H "X-Auth-Email: ${CF_ID}" \
        -H "X-Auth-Key: ${CF_KEY}" \
        -H "Content-Type: application/json" \
        --data '{"type":"A","name":"'${domain}'","content":"'${IP}'","proxied":false}')

    get_acme_domain
}

clear
echo -e "               ┌───────────────────────────────────────────────┐"
echo -e "───────────────│                                               │───────────────"
echo -e "───────────────│    $GREEN┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┬  ┬┌┬┐┌─┐$NC   │───────────────"
echo -e "───────────────│    $GREEN├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   │  │ │ ├┤ $NC   │───────────────"
echo -e "───────────────│    $GREEN┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴─┘┴ ┴ └─┘$NC   │───────────────"
echo -e "               │    ${ORANGE}Copyright${NC} (C)$LIGHT https://github.com/rullpqh$NC   │"
echo -e "               └───────────────────────────────────────────────┘"
echo -e "                      ${RED}Autoscript xray vpn lite (multi port)${NC}"
echo -e "            ${RED}Make sure the internet is smooth when installing the script${NC}"
echo -e "────────────────────────────────────────────────────────────────────────────────

                        ${GREEN}Hostname${NC}        :  $LAST_DOMAIN
                        ${GREEN}Public IP${NC}       :  $MYIP
                        ${GREEN}Total RAM${NC}       :  $totalram MB

─────────────────────────────────────────────────────────────────────────────────"
echo -e "1).${GREEN}MANUAL POINTING${NC}(Manual DNS-resolved IP address of the domain)"
echo -e "2).${GREEN}AUTO POINTING${NC}(Auto DNS-resolved IP address of the domain)"
read -p "between auto pointing / manual pointing what do you choose[ 1 - 2 ] : " NUM_MENU

case $NUM_MENU in
1)
    renew_domain
    ;;
2)
    cloudflare
    ;;
*)
    echo -e "${Red}You wrong command !${Font}"
    ;;
esac
